DROP TABLE IF EXISTS customer
DROP TABLE IF EXISTS account
CREATE TABLE customer (ID BIGINT NOT NULL, NAME VARCHAR(255), AGE INTEGER, PASSWORD VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE account (ID BIGINT NOT NULL, ACCOUNTNUMBER VARCHAR(255), BALANCE INTEGER, PRODUCT_FK BIGINT, PRIMARY KEY (ID))
ALTER TABLE account ADD CONSTRAINT FK_account_customer FOREIGN KEY (PRODUCT_FK) REFERENCES customer (ID)
